code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension AndrsDC.base16-themes
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension erd0s.terraform-autocomplete
code --install-extension esbenp.prettier-vscode
code --install-extension humao.rest-client
code --install-extension johnpapa.vscode-peacock
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension mauve.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.sublime-keybindings
code --install-extension PeterJausovec.vscode-docker
code --install-extension rogalmic.bash-debug
code --install-extension shakram02.bash-beautify
code --install-extension wix.vscode-import-cost
code --install-extension yummygum.city-lights-theme
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
code --install-extension ziyasal.vscode-open-in-github
